run:
  deadline: 3m
  modules-download-mode: readonly

linters-settings:
  gocyclo:
    min-complexity: 60
  gci:
    sections:
      - standard
      - default
      - prefix(d7y.io/dragonfly/v2)

issues:
  new: true
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019:"

linters:
  disable-all: true
  enable:
    - gci
    - gofmt
    - golint
    - misspell
    - govet
    - goconst
    - deadcode
    - gocyclo
    - staticcheck
    - errcheck

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
