coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        enabled: yes
        target: 35%
    patch:
      default:
        enabled: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  branches:
    - main
