apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "dragonfly.dfdaemon.fullname" . }}
  namespace: {{ template "dragonfly.namespace" . }}
  labels:
    app: {{ template "dragonfly.dfdaemon.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.dfdaemon.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if .Values.dfdaemon.daemonsetAnnotations }}
  annotations:
{{ toYaml .Values.dfdaemon.daemonsetAnnotations | indent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "dragonfly.dfdaemon.fullname" . }}
      component: "{{ .Values.dfdaemon.name }}"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "dragonfly.dfdaemon.fullname" . }}
        component: "{{ .Values.dfdaemon.name }}"
        release: {{ .Release.Name }}
        {{- if .Values.dfdaemon.podLabels }}
{{ toYaml .Values.dfdaemon.podLabels | indent 8 }}
        {{- end }}
      {{- if .Values.dfdaemon.podAnnotations }}
      annotations:
{{ toYaml .Values.dfdaemon.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      {{- if .Values.dfdaemon.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.dfdaemon.nodeSelector | indent 8 }}
      {{- end }}
      hostNetwork: {{ .Values.dfdaemon.hostNetwork }}
      {{- if .Values.dfdaemon.tolerations }}
      tolerations:
{{ toYaml .Values.dfdaemon.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.dfdaemon.affinity }}
      affinity:
{{ toYaml .Values.dfdaemon.affinity | indent 8 }}
      {{- end }}
      {{- if quote .Values.dfdaemon.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.dfdaemon.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if and (.Capabilities.APIVersions.Has "scheduling.k8s.io/v1beta1") (.Values.dfdaemon.priorityClassName) }}
      priorityClassName: {{ .Values.dfdaemon.priorityClassName }}
      {{- end }}
      containers:
      - name: dfdaemon
        image: "{{ .Values.dfdaemon.image }}:{{ .Values.dfdaemon.tag }}"
        imagePullPolicy: {{ .Values.dfdaemon.pullPolicy | quote }}
        resources:
{{ toYaml .Values.dfdaemon.resources | indent 12 }}
        ports:
        - containerPort: {{ .Values.dfdaemon.containerPort }}
          {{- if and (not .Values.dfdaemon.hostNetwork) (empty .Values.dfdaemon.config.proxy.tcpListen.namespace) }}
          hostPort: {{ .Values.dfdaemon.hostPort }}
          hostIP: 127.0.0.1
          {{- end }}
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: "/etc/dragonfly"
        {{- if and (not .Values.dfdaemon.hostNetwork) .Values.dfdaemon.config.proxy.tcpListen.namespace }}
        - name: run
          mountPath: /run/dragonfly
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
        {{- end }}
      {{- if and (not .Values.dfdaemon.hostNetwork) .Values.dfdaemon.config.proxy.tcpListen.namespace }}
      initContainers:
      - name: mount-netns
        image: "{{ .Values.dfdaemon.image }}:{{ .Values.dfdaemon.tag }}"
        imagePullPolicy: {{ .Values.dfdaemon.pullPolicy | quote }}
        resources:
{{ toYaml .Values.dfdaemon.resources | indent 12 }}
        # FIXME dfget daemon only need /proc/1/ns/net and CAP_SYS_ADMIN
        # but containerd resolves the symbolic of /proc/1/ns/net from v1.5.0
        # due to /proc/1/ns/net is not a regular symbolic link, it always failed.
        # for keeping only CAP_SYS_ADMIN capability, use init container to bind mount only netns to /run/dragonfly/net
        # https://github.com/containerd/containerd/blob/v1.5.0/pkg/cri/opts/spec_linux.go#L171
        command:
        - /bin/sh
        - -cx
        - |-
          if [ ! -e "/run/dragonfly/net" ]; then
            touch /run/dragonfly/net
          fi
          i1=$(stat -L -c %i /host/ns/net)
          i2=$(stat -L -c %i /run/dragonfly/net)
          if [ "$i1" != "$i2" ]; then
            /bin/mount -o bind /host/ns/net /run/dragonfly/net
          fi
        volumeMounts:
        - name: hostns
          mountPath: /host/ns
        - name: run
          mountPath: /run/dragonfly
          # bind mount need Bidirectional to propagate into host
          mountPropagation: Bidirectional
        securityContext:
          # open /proc/1/ns need privilege permission
          privileged: true
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "dragonfly.dfdaemon.fullname" . }}
      {{- if and (not .Values.dfdaemon.hostNetwork) .Values.dfdaemon.config.proxy.tcpListen.namespace }}
      - name: hostns
        hostPath:
          path: /proc/1/ns
      - name: run
        hostPath:
          path: /run/dragonfly
          type: DirectoryOrCreate
      {{- end }}
