// Code generated by MockGen. DO NOT EDIT.
// Source: scheduler/scheduler/scheduler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	set "d7y.io/dragonfly/v2/pkg/container/set"
	resource "d7y.io/dragonfly/v2/scheduler/resource"
	gomock "github.com/golang/mock/gomock"
)

// MockScheduler is a mock of Scheduler interface.
type MockScheduler struct {
	ctrl     *gomock.Controller
	recorder *MockSchedulerMockRecorder
}

// MockSchedulerMockRecorder is the mock recorder for MockScheduler.
type MockSchedulerMockRecorder struct {
	mock *MockScheduler
}

// NewMockScheduler creates a new mock instance.
func NewMockScheduler(ctrl *gomock.Controller) *MockScheduler {
	mock := &MockScheduler{ctrl: ctrl}
	mock.recorder = &MockSchedulerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduler) EXPECT() *MockSchedulerMockRecorder {
	return m.recorder
}

// FindParent mocks base method.
func (m *MockScheduler) FindParent(arg0 context.Context, arg1 *resource.Peer, arg2 set.SafeSet) (*resource.Peer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindParent", arg0, arg1, arg2)
	ret0, _ := ret[0].(*resource.Peer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// FindParent indicates an expected call of FindParent.
func (mr *MockSchedulerMockRecorder) FindParent(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindParent", reflect.TypeOf((*MockScheduler)(nil).FindParent), arg0, arg1, arg2)
}

// ScheduleParent mocks base method.
func (m *MockScheduler) ScheduleParent(arg0 context.Context, arg1 *resource.Peer, arg2 set.SafeSet) ([]*resource.Peer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScheduleParent", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*resource.Peer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ScheduleParent indicates an expected call of ScheduleParent.
func (mr *MockSchedulerMockRecorder) ScheduleParent(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScheduleParent", reflect.TypeOf((*MockScheduler)(nil).ScheduleParent), arg0, arg1, arg2)
}
