// Code generated by MockGen. DO NOT EDIT.
// Source: d7y.io/dragonfly/v2/cdn/dynconfig (interfaces: DynconfigInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dynconfig "d7y.io/dragonfly/v2/cdn/dynconfig"
	gomock "github.com/golang/mock/gomock"
)

// MockDynconfigInterface is a mock of DynconfigInterface interface.
type MockDynconfigInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDynconfigInterfaceMockRecorder
}

// MockDynconfigInterfaceMockRecorder is the mock recorder for MockDynconfigInterface.
type MockDynconfigInterfaceMockRecorder struct {
	mock *MockDynconfigInterface
}

// NewMockDynconfigInterface creates a new mock instance.
func NewMockDynconfigInterface(ctrl *gomock.Controller) *MockDynconfigInterface {
	mock := &MockDynconfigInterface{ctrl: ctrl}
	mock.recorder = &MockDynconfigInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDynconfigInterface) EXPECT() *MockDynconfigInterfaceMockRecorder {
	return m.recorder
}

// Deregister mocks base method.
func (m *MockDynconfigInterface) Deregister(arg0 dynconfig.Observer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Deregister", arg0)
}

// Deregister indicates an expected call of Deregister.
func (mr *MockDynconfigInterfaceMockRecorder) Deregister(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deregister", reflect.TypeOf((*MockDynconfigInterface)(nil).Deregister), arg0)
}

// Get mocks base method.
func (m *MockDynconfigInterface) Get() (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDynconfigInterfaceMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDynconfigInterface)(nil).Get))
}

// Notify mocks base method.
func (m *MockDynconfigInterface) Notify() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify")
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockDynconfigInterfaceMockRecorder) Notify() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockDynconfigInterface)(nil).Notify))
}

// Register mocks base method.
func (m *MockDynconfigInterface) Register(arg0 dynconfig.Observer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", arg0)
}

// Register indicates an expected call of Register.
func (mr *MockDynconfigInterfaceMockRecorder) Register(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockDynconfigInterface)(nil).Register), arg0)
}

// Serve mocks base method.
func (m *MockDynconfigInterface) Serve() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Serve")
	ret0, _ := ret[0].(error)
	return ret0
}

// Serve indicates an expected call of Serve.
func (mr *MockDynconfigInterfaceMockRecorder) Serve() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Serve", reflect.TypeOf((*MockDynconfigInterface)(nil).Serve))
}

// Stop mocks base method.
func (m *MockDynconfigInterface) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockDynconfigInterfaceMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockDynconfigInterface)(nil).Stop))
}
